import { Metadata } from "next";
import { Lato } from "next/font/google";

import "./globals.css";
import { CongesLayout } from "@/layout/CongesLayout";

const lato = Lato({
  weight: ["400", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-lato",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${lato.className} overflow-hidden text-sm antialiased`}
        cz-shortcut-listen="true"
      >
        <CongesLayout>{children}</CongesLayout>
      </body>
    </html>
  );
};
export default RootLayout;
